# Generated by Django 4.0.1 on 2022-01-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('inicio', models.TimeField()),
                ('final', models.TimeField()),
                ('sala', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
